[package]
name = "yaminabe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
sudo = "0.6.0"
uuid = "1.8.0"
wait-timeout = "0.2.0"
