package internal

import "golang.org/x/sys/unix"

var mountFlagMap = map[string]uintptr{
	"async":         unix.MS_ASYNC,
	"atime":         0,
	"bind":          unix.MS_BIND,
	"defaults":      0,
	"dev":           unix.MS_NODEV,
	"diratime":      0,
	"dirsync":       unix.MS_DIRSYNC,
	"exec":          0,
	"iversion":      unix.MS_I_VERSION,
	"lazytime":      unix.MS_LAZYTIME,
	"loud":          0,
	"noatime":       unix.MS_NOATIME,
	"nodev":         unix.MS_NODEV,
	"nodiratime":    unix.MS_NODIRATIME,
	"noexec":        unix.MS_NOEXEC,
	"noiversion":    0,
	"nolazytime":    unix.MS_RELATIME,
	"norelatime":    unix.MS_RELATIME,
	"nostrictatime": unix.MS_RELATIME,
	"nosuid":        unix.MS_NOSUID,
	"private":       unix.MS_PRIVATE,
	"rbind":         unix.MS_BIND | unix.MS_REC,
	"rdev":          unix.MS_NODEV | unix.MS_REC,
	"rdiratime":     0 | unix.MS_REC,
	"relatime":      unix.MS_RELATIME,
	"remount":       unix.MS_REMOUNT,
	"ro":            unix.MS_RDONLY,
	"rprivate":      unix.MS_PRIVATE | unix.MS_REC,
	"rshared":       unix.MS_SHARED | unix.MS_REC,
	"rslave":        unix.MS_SLAVE | unix.MS_REC,
	"runbindable":   unix.MS_UNBINDABLE | unix.MS_REC,
	"rw":            0,
	"shared":        unix.MS_SHARED,
	"silent":        0,
	"slave":         unix.MS_SLAVE,
	"strictatime":   unix.MS_STRICTATIME,
	"suid":          0,
	"sync":          unix.MS_SYNC,
	"unbindable":    unix.MS_UNBINDABLE,
}
